-- Paste into the Supabase SQL editor. Safe to run twice.
--
-- Generated by scripts/supabase-build-apply.mjs. Do not edit by hand:
-- edit the migrations under supabase/migrations/ and run the script again.
--
-- Parts, in order: 20260915000050_baseline_live_objects.sql, 20260915000100_leads.sql, 20260915000200_profiles_rpc.sql

-- ====================================================================
-- 20260915000050_baseline_live_objects.sql
-- ====================================================================

-- Baseline of the objects that already exist in the live project but had no
-- SQL in this repo until 15 September 2026. Captured from the live schema
-- (pg_get_functiondef, pg_policies) so a fresh project can be rebuilt from
-- the repo alone. Idempotent: every statement is create-if-not-exists,
-- create-or-replace, or drop-policy-if-exists followed by create.
--
-- Not covered on purpose: game_state (referenced by dead code, never
-- created), the feedback-notify trigger function (depends on an edge
-- function and the net extension), and the telemetry anon grant (the app
-- inserts with the anon key but the live policy only allows authenticated,
-- see the follow-ups in HANDOFF.md).

-- waitlist RPCs -------------------------------------------------------------

create or replace function public.waitlist_count()
returns bigint
language sql
stable
security definer
set search_path = public
as $fn$
  select count(*) from public.waitlist;
$fn$;

revoke all on function public.waitlist_count() from public;
grant execute on function public.waitlist_count() to anon, authenticated;

create or replace function public.update_waitlist_screener(
  p_email text,
  p_child_age text,
  p_challenge text,
  p_willing_to_test text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $fn$
declare
  rows_updated int;
begin
  update public.waitlist
  set child_age = p_child_age,
      challenge = p_challenge,
      willing_to_test = p_willing_to_test,
      screener_completed_at = now()
  where lower(email) = lower(p_email)
    and screener_completed_at is null;

  get diagnostics rows_updated = row_count;
  return rows_updated > 0;
end;
$fn$;

revoke all on function public.update_waitlist_screener(text, text, text, text) from public;
grant execute on function public.update_waitlist_screener(text, text, text, text) to anon, authenticated;

-- site_feedback (anonymous website feedback) ------------------------------

create table if not exists public.site_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  message text not null,
  email text,
  source text,
  locale text not null default 'de'
);

alter table public.site_feedback enable row level security;

drop policy if exists "site_feedback_anon_insert" on public.site_feedback;
create policy "site_feedback_anon_insert"
  on public.site_feedback
  for insert
  to anon
  with check (
    length(message) >= 4 and length(message) <= 4000
    and (email is null or email ~ '^[^\s@]+@[^\s@]+\.[^\s@]+$')
  );

grant insert on public.site_feedback to anon;

-- feedback (in-app, authenticated users) ----------------------------------

create table if not exists public.feedback (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  message text not null,
  screen text,
  ronki_stage integer,
  cat_evo integer,
  app_version text,
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

drop policy if exists "Users can insert own feedback" on public.feedback;
create policy "Users can insert own feedback"
  on public.feedback
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can read own feedback" on public.feedback;
create policy "Users can read own feedback"
  on public.feedback
  for select
  to authenticated
  using (auth.uid() = user_id);

grant insert, select on public.feedback to authenticated;

-- app_evals (the App-Check tool on the website) ---------------------------

create table if not exists public.app_evals (
  id text primary key,
  app_name text not null,
  app_id_curated text,
  answers jsonb not null,
  score smallint not null,
  created_at timestamptz not null default now(),
  client_locale text not null default 'de'
);

do $do$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.app_evals'::regclass and conname = 'app_evals_score_check'
  ) then
    alter table public.app_evals
      add constraint app_evals_score_check check (score >= 0 and score <= 10);
  end if;
end
$do$;

alter table public.app_evals enable row level security;

drop policy if exists "anyone_can_insert_eval" on public.app_evals;
create policy "anyone_can_insert_eval"
  on public.app_evals
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "anyone_can_read_evals" on public.app_evals;
create policy "anyone_can_read_evals"
  on public.app_evals
  for select
  to anon, authenticated
  using (true);

grant insert, select on public.app_evals to anon, authenticated;

create or replace view public.app_eval_counts as
  select app_name, count(*)::integer as n
  from public.app_evals
  group by app_name;

grant select on public.app_eval_counts to anon, authenticated;

-- ====================================================================
-- 20260915000100_leads.sql
-- ====================================================================

-- Ronki leads: parent email capture on the Vorlagen download pages.
--
-- Funnel gate for the revival check (docs/strategy/2026-09-14-wiederbelebungs-check.md):
-- the templates rank close to page 1 but there is no download behind them.
-- A lead row is one parent asking for one template.
--
-- Privacy: parent email only, no child data, no names. Consent is required
-- by a CHECK constraint, and the consent wording that was on screen is stored
-- alongside it so we can prove what the parent agreed to.
--
-- Idempotent. Safe to run twice.

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  email text not null,
  source text not null,
  consent boolean not null default false,
  consent_text text,
  wants_updates boolean not null default false,
  locale text not null default 'de'
);

-- Column guards, in case a partial table already exists. Only columns with
-- a default are guarded this way; email and source are part of the create
-- above and must stay not null.
alter table public.leads add column if not exists created_at timestamptz not null default now();
alter table public.leads add column if not exists consent boolean not null default false;
alter table public.leads add column if not exists consent_text text;
alter table public.leads add column if not exists wants_updates boolean not null default false;
alter table public.leads add column if not exists locale text not null default 'de';

-- CHECK constraints. Postgres has no "add constraint if not exists",
-- so each one is guarded by a lookup in pg_constraint.
do $do$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.leads'::regclass and conname = 'leads_email_format'
  ) then
    alter table public.leads
      add constraint leads_email_format
      check (email ~ '^[^\s@]+@[^\s@]+\.[^\s@]+$');
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.leads'::regclass and conname = 'leads_email_length'
  ) then
    alter table public.leads
      add constraint leads_email_length
      check (char_length(email) <= 254);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.leads'::regclass and conname = 'leads_source_allowed'
  ) then
    alter table public.leads
      add constraint leads_source_allowed
      check (source in (
        'vorlage-morgen',
        'vorlage-abend',
        'vorlage-kleine-geschwister',
        'vorlage-adhs'
      ));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.leads'::regclass and conname = 'leads_consent_required'
  ) then
    alter table public.leads
      add constraint leads_consent_required
      check (consent = true);
  end if;
end
$do$;

-- One row per parent per template. A repeat download is not a new lead.
create unique index if not exists leads_email_source_idx
  on public.leads (email, source);

create index if not exists leads_created_at_idx
  on public.leads (created_at desc);

alter table public.leads enable row level security;

-- Anon may insert and nothing else. The CHECK constraints above do the
-- validation, so the policy itself stays open on purpose.
drop policy if exists "anon insert leads" on public.leads;
create policy "anon insert leads"
  on public.leads
  for insert
  to anon
  with check (true);

-- No select, update or delete policy for anon. RLS denies those by default.
revoke all on public.leads from anon;
grant insert on public.leads to anon;

comment on table public.leads is 'Ronki template download leads. Parent emails only, consent required.';
comment on column public.leads.source is 'Which template page the parent came from.';
comment on column public.leads.consent_text is 'The consent wording shown on screen at the time of signup.';
comment on column public.leads.wants_updates is 'Second, optional checkbox: the parent wants occasional update mails.';

-- Public counter for the funnel gate. Counts a parent once, whether they
-- arrived through a template download or the waitlist.
create or replace function public.leads_count()
returns integer
language sql
security definer
set search_path = public
as $fn$
  select count(*)::integer from (
    select lower(email) as email from public.leads
    union
    select lower(email) as email from public.waitlist
  ) combined;
$fn$;

revoke all on function public.leads_count() from public;
grant execute on function public.leads_count() to anon, authenticated;

-- ====================================================================
-- 20260915000200_profiles_rpc.sql
-- ====================================================================

-- Ronki profiles: close the privacy gap and add the activity counter.
--
-- Before this migration anon could LIST public.profiles, which means anyone
-- with the public anon key could read every child profile and every token.
-- The token is the credential (see docs/specs/qr-profile-auth.md), so a
-- listable table hands out every family's login.
--
-- After this migration nothing reaches public.profiles directly. All access
-- goes through four security definer functions that take the token as an
-- argument, so a caller can only touch the profile whose token they already
-- hold. Table grants for anon are revoked and every old policy is dropped.
--
-- public.profile_activity records one row per token per day. It is what
-- "active family" means for the 30 day decision in
-- docs/strategy/2026-09-14-wiederbelebungs-check.md, and it replaces the
-- old last_active_at single timestamp for that purpose.
--
-- Idempotent. Safe to run twice.

create table if not exists public.profile_activity (
  token text not null,
  day date not null,
  primary key (token, day)
);

create index if not exists profile_activity_day_idx
  on public.profile_activity (day desc);

alter table public.profile_activity enable row level security;

-- No policies for anon on purpose. RLS with no policy denies everything.
revoke all on public.profile_activity from anon;

comment on table public.profile_activity is 'One row per profile token per day it was written. Feeds profiles_active_count().';

-- profiles already exists live. The create below is the shape of record for
-- a fresh project; the add column guards bring an existing table in line.
create table if not exists public.profiles (
  token text primary key,
  state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists created_at timestamptz not null default now();
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

-- Read one profile by its token. Returns null when there is no such row,
-- which the app treats exactly like "no cloud state yet".
create or replace function public.profile_get(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_state jsonb;
  v_updated_at timestamptz;
begin
  select state, updated_at
    into v_state, v_updated_at
    from public.profiles
   where token = p_token;

  if not found then
    return null;
  end if;

  return jsonb_build_object('state', v_state, 'updated_at', v_updated_at);
end;
$fn$;

-- Write one profile by its token and stamp today into profile_activity.
-- The token shape is enforced here so a malformed token cannot create rows.
create or replace function public.profile_upsert(p_token text, p_state jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_updated_at timestamptz;
begin
  if p_token is null or p_token !~ '^[0-9a-f]{32}$' then
    raise exception 'invalid token';
  end if;

  insert into public.profiles as p (token, state, updated_at)
  values (p_token, coalesce(p_state, '{}'::jsonb), now())
  on conflict (token) do update
    set state = excluded.state,
        updated_at = now()
  returning p.updated_at into v_updated_at;

  insert into public.profile_activity (token, day)
  values (p_token, current_date)
  on conflict do nothing;

  return jsonb_build_object('updated_at', v_updated_at);
end;
$fn$;

-- Delete one profile and its activity rows. True when a profile row went away.
create or replace function public.profile_delete(p_token text)
returns boolean
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_deleted integer;
begin
  delete from public.profile_activity where token = p_token;

  delete from public.profiles where token = p_token;
  get diagnostics v_deleted = row_count;

  return v_deleted > 0;
end;
$fn$;

-- How many cards exist at all.
create or replace function public.profiles_count()
returns integer
language sql
security definer
set search_path = public
as $fn$
  select count(*)::integer from public.profiles;
$fn$;

-- How many cards came back on at least p_min_days separate days since p_since.
-- This is the "real families" number, not the "someone clicked once" number.
create or replace function public.profiles_active_count(
  p_min_days integer default 3,
  p_since timestamptz default now() - interval '60 days'
)
returns integer
language sql
security definer
set search_path = public
as $fn$
  select count(*)::integer from (
    select token
      from public.profile_activity
     where day >= (p_since)::date
     group by token
    having count(distinct day) >= p_min_days
  ) active;
$fn$;

revoke all on function public.profile_get(text) from public;
revoke all on function public.profile_upsert(text, jsonb) from public;
revoke all on function public.profile_delete(text) from public;
revoke all on function public.profiles_count() from public;
revoke all on function public.profiles_active_count(integer, timestamptz) from public;

grant execute on function public.profile_get(text) to anon, authenticated;
grant execute on function public.profile_upsert(text, jsonb) to anon, authenticated;
grant execute on function public.profile_delete(text) to anon, authenticated;
grant execute on function public.profiles_count() to anon, authenticated;
grant execute on function public.profiles_active_count(integer, timestamptz) to anon, authenticated;

-- Tighten profiles last, once the functions that replace direct access exist.
-- Every policy on the table goes, whatever it was called. The permissive
-- policies that let anon list profiles were never in the repo, so this is a
-- one way door: see supabase/README.md.
do $do$
declare
  r record;
begin
  for r in
    select policyname
      from pg_policies
     where schemaname = 'public'
       and tablename = 'profiles'
  loop
    execute format('drop policy if exists %I on public.profiles', r.policyname);
  end loop;
end
$do$;

alter table public.profiles enable row level security;
revoke all on public.profiles from anon;

comment on table public.profiles is 'Kid profiles keyed by a 32 hex token. No direct anon access: use profile_get, profile_upsert, profile_delete.';
