-- Baseline of the objects that already exist in the live project but had no
-- SQL in this repo until 15 September 2026. Captured from the live schema
-- (pg_get_functiondef, pg_policies) so a fresh project can be rebuilt from
-- the repo alone. Idempotent: every statement is create-if-not-exists,
-- create-or-replace, or drop-policy-if-exists followed by create.
--
-- Not covered on purpose: game_state (referenced by dead code, never
-- created), the feedback-notify trigger function (depends on an edge
-- function and the net extension), and the telemetry anon grant (the app
-- inserts with the anon key but the live policy only allows authenticated,
-- see the follow-ups in HANDOFF.md).

-- waitlist RPCs -------------------------------------------------------------

create or replace function public.waitlist_count()
returns bigint
language sql
stable
security definer
set search_path = public
as $fn$
  select count(*) from public.waitlist;
$fn$;

revoke all on function public.waitlist_count() from public;
grant execute on function public.waitlist_count() to anon, authenticated;

create or replace function public.update_waitlist_screener(
  p_email text,
  p_child_age text,
  p_challenge text,
  p_willing_to_test text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $fn$
declare
  rows_updated int;
begin
  update public.waitlist
  set child_age = p_child_age,
      challenge = p_challenge,
      willing_to_test = p_willing_to_test,
      screener_completed_at = now()
  where lower(email) = lower(p_email)
    and screener_completed_at is null;

  get diagnostics rows_updated = row_count;
  return rows_updated > 0;
end;
$fn$;

revoke all on function public.update_waitlist_screener(text, text, text, text) from public;
grant execute on function public.update_waitlist_screener(text, text, text, text) to anon, authenticated;

-- site_feedback (anonymous website feedback) ------------------------------

create table if not exists public.site_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  message text not null,
  email text,
  source text,
  locale text not null default 'de'
);

alter table public.site_feedback enable row level security;

drop policy if exists "site_feedback_anon_insert" on public.site_feedback;
create policy "site_feedback_anon_insert"
  on public.site_feedback
  for insert
  to anon
  with check (
    length(message) >= 4 and length(message) <= 4000
    and (email is null or email ~ '^[^\s@]+@[^\s@]+\.[^\s@]+$')
  );

grant insert on public.site_feedback to anon;

-- feedback (in-app, authenticated users) ----------------------------------

create table if not exists public.feedback (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  message text not null,
  screen text,
  ronki_stage integer,
  cat_evo integer,
  app_version text,
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

drop policy if exists "Users can insert own feedback" on public.feedback;
create policy "Users can insert own feedback"
  on public.feedback
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can read own feedback" on public.feedback;
create policy "Users can read own feedback"
  on public.feedback
  for select
  to authenticated
  using (auth.uid() = user_id);

grant insert, select on public.feedback to authenticated;

-- app_evals (the App-Check tool on the website) ---------------------------

create table if not exists public.app_evals (
  id text primary key,
  app_name text not null,
  app_id_curated text,
  answers jsonb not null,
  score smallint not null,
  created_at timestamptz not null default now(),
  client_locale text not null default 'de'
);

do $do$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.app_evals'::regclass and conname = 'app_evals_score_check'
  ) then
    alter table public.app_evals
      add constraint app_evals_score_check check (score >= 0 and score <= 10);
  end if;
end
$do$;

alter table public.app_evals enable row level security;

drop policy if exists "anyone_can_insert_eval" on public.app_evals;
create policy "anyone_can_insert_eval"
  on public.app_evals
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "anyone_can_read_evals" on public.app_evals;
create policy "anyone_can_read_evals"
  on public.app_evals
  for select
  to anon, authenticated
  using (true);

grant insert, select on public.app_evals to anon, authenticated;

create or replace view public.app_eval_counts as
  select app_name, count(*)::integer as n
  from public.app_evals
  group by app_name;

grant select on public.app_eval_counts to anon, authenticated;
